namespace StarkFiRentalClient;

public static class Program
{
    private static LockForm _lockForm = null!;
    private static CountdownWidget _widget = null!;
    private static bool _lockShowing = true;

    [STAThread]
    public static void Main()
    {
        // Classic explicit setup rather than ApplicationConfiguration.
        // Initialize() - that helper is only auto-generated by the
        // `dotnet new winforms` template's project settings, which this
        // hand-written .csproj doesn't opt into.
        Application.SetHighDpiMode(HighDpiMode.SystemAware);
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);

        var config = ClientConfig.Load();
        if (config == null || string.IsNullOrEmpty(config.ServerUrl))
        {
            // Try to find the server automatically first (same UDP
            // broadcast protocol ESP32 Vendos already use to find this
            // box - see ServerDiscovery.cs) - manual entry stays
            // available either way, just pre-filled when discovery
            // succeeds so a tech can confirm with Enter or type a
            // different address if this PC is on a different network.
            var discovered = ServerDiscovery.TryDiscoverAsync().GetAwaiter().GetResult();
            var promptLabel = discovered != null
                ? "Found a StarkFi server automatically - press Enter to use it, or type a different address:"
                : "Server address (e.g. http://192.168.1.10:3000):";
            var serverUrl = PromptDialog.Show("StarkFi Rental Setup", promptLabel, defaultValue: discovered ?? "");
            if (string.IsNullOrWhiteSpace(serverUrl))
            {
                MessageBox.Show("A server address is required to continue.", "StarkFi Rental", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }
            config = new ClientConfig { ServerUrl = serverUrl.Trim(), Mac = ClientConfig.GetMacAddress() };
        }

        var api = new RentalApiClient(config.ServerUrl);

        // Register (or re-register/heartbeat) synchronously before showing
        // any UI - if this PC isn't paired yet, this is what pairs it.
        try
        {
            var registerResult = api.RegisterAsync(config.Mac, Environment.MachineName, string.IsNullOrEmpty(config.DeviceSecret) ? null : config.DeviceSecret)
                .GetAwaiter().GetResult();
            if (registerResult?.Success == true && !string.IsNullOrEmpty(registerResult.DeviceSecret))
            {
                config.DeviceSecret = registerResult.DeviceSecret;
                if (registerResult.PcId > 0) config.PcId = registerResult.PcId;
                config.Save();
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Could not reach the StarkFi server at {config.ServerUrl}:\n{ex.Message}\n\nWill keep retrying in the background.",
                "StarkFi Rental", MessageBoxButtons.OK, MessageBoxIcon.Warning);
        }

        _lockForm = new LockForm(api, config);
        _widget = new CountdownWidget(api, config);

        var poller = new StatusPoller(api, config);
        poller.StatusUpdated += status =>
        {
            // Timer callbacks run off the UI thread - every UI touch has
            // to be marshaled back via Invoke.
            if (_lockForm.IsHandleCreated)
            {
                _lockForm.BeginInvoke(() => HandleStatus(status));
            }
        };
        poller.ConnectionLost += () =>
        {
            if (_lockForm.IsHandleCreated)
            {
                _lockForm.BeginInvoke(() => ShowLockDefensively());
            }
        };
        poller.Start();

        Application.Run(_lockForm);
    }

    private static void HandleStatus(StatusResponse status)
    {
        if (status.Paused)
        {
            // Staff maintenance pause - neither the full lock screen nor
            // the normal countdown; reuse the countdown widget's corner
            // window with paused content instead of a third window type.
            _lockShowing = false;
            _lockForm.HideLock();
            _widget.ShowPaused();
            if (!_widget.Visible) _widget.Show();
        }
        else if (status.Locked)
        {
            _widget.Hide();
            if (!_lockShowing)
            {
                _lockShowing = true;
            }
            _lockForm.ShowLock(status);
        }
        else
        {
            _lockShowing = false;
            _lockForm.HideLock();
            _widget.UpdateFromStatus(status);
            if (!_widget.Visible) _widget.Show();
        }
    }

    private static void ShowLockDefensively()
    {
        // Lost contact with the server for ~15s straight - don't trust
        // whatever the last known "unlocked" state was, lock now. The
        // poller keeps trying in the background; the moment it succeeds
        // again, HandleStatus takes over normally.
        if (!_lockShowing)
        {
            _lockShowing = true;
            _widget.Hide();
            _lockForm.Show();
        }
    }
}
