const fs = require('fs');
const path = require('path');
const { execFile, execSync } = require('child_process');

// Refreshes the pre-login console banner (/etc/issue) so it reflects the
// IP actually assigned instead of the boot-time snapshot setup-network.sh
// wrote before this static IP was applied. Best-effort - a box without a
// physical/serial console attached, or one where the sudoers grant for
// this script hasn't been provisioned, just keeps running normally.
const CONSOLE_BANNER_SCRIPT = path.join(__dirname, '..', '..', 'setup', 'update-console-banner.sh');
function refreshConsoleBanner() {
  execFile('sudo', ['bash', CONSOLE_BANNER_SCRIPT], { timeout: 5000 }, (err) => {
    if (err) console.error('Could not refresh console banner:', err.message);
  });
}

// Real bug found live: this used to detect the interface purely from
// "whatever currently holds the default route" - fine once the box is
// already up and running, but reapplyStaticNetworkOnBoot() calls this right
// at server startup, immediately after setup-network.sh disabled DHCP on
// this exact interface and (in the untagged case) left it addressless on
// purpose, expecting this function to give it its static address. At that
// moment there's no default route yet, so detection silently fell back to a
// hardcoded "enp0s3" - wrong on any box actually using enp0s8 (this whole
// project's dev/test VM has flip-flopped between the two across boots) -
// writing the static IP to the wrong interface and leaving the real one on
// whatever DHCP/cloud-init default it had. setup-network.sh already knows
// the real LAN interface name (the same 'lan_interface' setting it reads
// itself) - reuse that as the primary source of truth, and only fall back
// to route-detection (still useful standalone, e.g. before any interface
// has ever been configured) when it's unset.
function getPrimaryInterface() {
  try {
    const db = require('../config/database');
    const saved = db.prepare("SELECT value FROM settings WHERE key = 'lan_interface'").get()?.value;
    if (saved) return saved;
  } catch (err) {
    console.error('Could not read saved LAN interface:', err.message);
  }
  try {
    const out = execSync('ip route show default', { encoding: 'utf8' });
    const match = out.match(/dev (\S+)/);
    if (match) return match[1];
  } catch (err) {
    console.error('Could not detect primary interface:', err.message);
  }
  return 'enp0s3';
}

// Writes and applies a netplan config for {type, ip, gateway, dns, subnet}.
// Written to 95-rj-pisowifi.yaml (not 50-cloud-init.yaml) - that file is
// regenerated by cloud-init on every boot, so anything written there was
// silently wiped back to DHCP on next reboot. Also has to sort after
// setup-network.sh's own 90-rj-pisowifi-${iface}.yaml (which only turns OS
// DHCP off for the interface, it doesn't assign an address) - with the old
// 60-... name, that 90-file's dhcp4:false won the per-key netplan merge
// over this file's dhcp4:true during a DHCP fallback, leaving the
// interface addressless instead of actually reachable. 95 always wins over
// both.
function applyNetworkConfig({ type, ip, gateway, dns, subnet }) {
  const iface = getPrimaryInterface();
  let netplanConfig = '';
  if (type === 'dhcp') {
    netplanConfig = `network:\n  ethernets:\n    ${iface}:\n      dhcp4: true\n  version: 2\n`;
  } else {
    netplanConfig = `network:\n  ethernets:\n    ${iface}:\n      dhcp4: false\n      addresses:\n        - ${ip}/${subnet || '24'}\n      routes:\n        - to: default\n          via: ${gateway}\n      nameservers:\n        addresses:\n          - ${dns || '8.8.8.8'}\n          - 8.8.4.4\n  version: 2\n`;
  }

  return new Promise((resolve, reject) => {
    const tmpFile = '/tmp/rj-network-' + Date.now() + '.yaml';
    fs.writeFileSync(tmpFile, netplanConfig, { mode: 0o600 });

    execFile('sudo', ['cp', tmpFile, '/etc/netplan/95-rj-pisowifi.yaml'], { timeout: 5000 }, (err) => {
      fs.unlinkSync(tmpFile);
      if (err) return reject(err);

      // Remove the old 60-numbered file from earlier builds - it can be
      // left over from before this moved to 95-, and a stale copy sitting
      // on disk with different values than what we just wrote would still
      // merge into the interface's config alongside this one.
      execFile('sudo', ['rm', '-f', '/etc/netplan/60-rj-pisowifi.yaml'], { timeout: 5000 }, () => {
        execFile('sudo', ['netplan', 'apply'], { timeout: 5000 }, (err2) => {
          if (err2) return reject(err2);
          resolve();
        });
      });
    });
  });
}

// Bug: the saved static IP only ever took effect the moment someone clicked
// "Apply Network Settings" in the admin panel - after any reboot (a VM
// restart, a power outage, an adapter swap) the box came back on whatever
// cloud-init/DHCP handed it, silently drifting away from the IP the rest of
// the setup (MikroTik reservations, walled-garden rules, port forwards)
// assumed it was on. Re-running the same apply logic at server startup
// closes that gap without requiring anyone to be there to click the button.
async function reapplyStaticNetworkOnBoot(db) {
  try {
    const type = db.prepare("SELECT value FROM settings WHERE key = 'network_type'").get()?.value;
    if (type !== 'static') return;

    const ip = db.prepare("SELECT value FROM settings WHERE key = 'static_ip'").get()?.value;
    const gateway = db.prepare("SELECT value FROM settings WHERE key = 'static_gateway'").get()?.value;
    const dns = db.prepare("SELECT value FROM settings WHERE key = 'static_dns'").get()?.value;
    const subnet = db.prepare("SELECT value FROM settings WHERE key = 'static_subnet'").get()?.value;
    if (!ip || !gateway) return;

    await applyNetworkConfig({ type: 'static', ip, gateway, dns, subnet });
    console.log(`🌐 Static IP re-applied on boot: ${ip}`);
    refreshConsoleBanner();
  } catch (err) {
    console.error('Could not re-apply static network config on boot:', err.message);
  }
}

let consecutiveFailures = 0;
const FAILURE_THRESHOLD = 3;
let strandedOnTemporaryDhcp = false;

// Fallback design principle: a static IP that outlives the network it was
// set for is exactly the kind of single point of failure a feature should
// never create. If someone sets a static IP, then moves the box to a
// different router or ISP without switching back to DHCP first (the
// warning in the admin panel is easy to miss or forget), the server goes
// completely unreachable with no way back in short of physical console
// access. This checks the configured gateway periodically.
//
// The fallback itself is deliberately temporary and never touches the
// saved `network_type`/`static_ip` settings - those stay 'static' the
// whole time, so the box keeps trying the real gateway on every tick and
// switches itself back the moment it's reachable again. Earlier this
// persisted network_type='dhcp' to the DB on fallback, which meant any
// gateway blip longer than 9 minutes silently and permanently abandoned
// the configured static IP - an operator had to notice and manually
// re-enter it every time. That defeated the point of "static": it should
// self-heal back to the fixed IP on its own, not require babysitting.
function checkStaticConnectivity(db) {
  try {
    const type = db.prepare("SELECT value FROM settings WHERE key = 'network_type'").get()?.value;
    if (type !== 'static') {
      consecutiveFailures = 0;
      strandedOnTemporaryDhcp = false;
      return;
    }

    const gateway = db.prepare("SELECT value FROM settings WHERE key = 'static_gateway'").get()?.value;
    if (!gateway) return;

    execFile('ping', ['-c', '1', '-W', '2', gateway], (err) => {
      if (!err) {
        consecutiveFailures = 0;
        if (strandedOnTemporaryDhcp) {
          console.log(`🌐 Static gateway ${gateway} reachable again, restoring configured static IP`);
          const ip = db.prepare("SELECT value FROM settings WHERE key = 'static_ip'").get()?.value;
          const dns = db.prepare("SELECT value FROM settings WHERE key = 'static_dns'").get()?.value;
          const subnet = db.prepare("SELECT value FROM settings WHERE key = 'static_subnet'").get()?.value;
          applyNetworkConfig({ type: 'static', ip, gateway, dns, subnet })
            .then(() => {
              strandedOnTemporaryDhcp = false;
              console.log(`🌐 Static IP restored: ${ip}`);
              refreshConsoleBanner();
            })
            .catch((restoreErr) => console.error('Could not restore static IP:', restoreErr.message));
        }
        return;
      }

      consecutiveFailures++;
      console.warn(`🌐 Static gateway ${gateway} unreachable (${consecutiveFailures}/${FAILURE_THRESHOLD})`);

      if (consecutiveFailures >= FAILURE_THRESHOLD && !strandedOnTemporaryDhcp) {
        consecutiveFailures = 0;
        console.warn('🌐 Static IP unreachable for too long, temporarily using DHCP so this box stays reachable (saved static config is untouched and will be restored automatically)');
        applyNetworkConfig({ type: 'dhcp' })
          .then(() => {
            strandedOnTemporaryDhcp = true;
            console.log('🌐 Temporarily on DHCP - will keep checking the real gateway and switch back automatically');
          })
          .catch((fallbackErr) => {
            console.error('Could not fall back to DHCP:', fallbackErr.message);
          });
      }
    });
  } catch (err) {
    console.error('Connectivity watchdog error:', err.message);
  }
}

function startConnectivityWatchdog(db) {
  const cron = require('node-cron');
  cron.schedule('*/3 * * * *', () => checkStaticConnectivity(db));
}

module.exports = { getPrimaryInterface, applyNetworkConfig, reapplyStaticNetworkOnBoot, startConnectivityWatchdog, refreshConsoleBanner };
