const fs = require('fs');
const { execFile, execSync } = require('child_process');

// Reads the interface currently holding the default route instead of a
// hardcoded name - a VirtualBox adapter swap (or any NIC rename) used to
// silently break static-IP apply because it kept targeting "enp0s3" even
// after the box was actually running on a different interface.
function getPrimaryInterface() {
  try {
    const out = execSync('ip route show default', { encoding: 'utf8' });
    const match = out.match(/dev (\S+)/);
    if (match) return match[1];
  } catch (err) {
    console.error('Could not detect primary interface:', err.message);
  }
  return 'enp0s3';
}

// Writes and applies a netplan config for {type, ip, gateway, dns, subnet}.
// Written to 60-rj-pisowifi.yaml (not 50-cloud-init.yaml) - that file is
// regenerated by cloud-init on every boot, so anything written there was
// silently wiped back to DHCP on next reboot. A filename sorting after it
// wins the netplan merge on matching keys without needing cloud-init
// involved.
function applyNetworkConfig({ type, ip, gateway, dns, subnet }) {
  const iface = getPrimaryInterface();
  let netplanConfig = '';
  if (type === 'dhcp') {
    netplanConfig = `network:\n  ethernets:\n    ${iface}:\n      dhcp4: true\n  version: 2\n`;
  } else {
    netplanConfig = `network:\n  ethernets:\n    ${iface}:\n      dhcp4: false\n      addresses:\n        - ${ip}/${subnet || '24'}\n      routes:\n        - to: default\n          via: ${gateway}\n      nameservers:\n        addresses:\n          - ${dns || '8.8.8.8'}\n          - 8.8.4.4\n  version: 2\n`;
  }

  return new Promise((resolve, reject) => {
    const tmpFile = '/tmp/rj-network-' + Date.now() + '.yaml';
    fs.writeFileSync(tmpFile, netplanConfig, { mode: 0o600 });

    execFile('sudo', ['cp', tmpFile, '/etc/netplan/60-rj-pisowifi.yaml'], { timeout: 5000 }, (err) => {
      fs.unlinkSync(tmpFile);
      if (err) return reject(err);

      execFile('sudo', ['netplan', 'apply'], { timeout: 5000 }, (err2) => {
        if (err2) return reject(err2);
        resolve();
      });
    });
  });
}

// Bug: the saved static IP only ever took effect the moment someone clicked
// "Apply Network Settings" in the admin panel - after any reboot (a VM
// restart, a power outage, an adapter swap) the box came back on whatever
// cloud-init/DHCP handed it, silently drifting away from the IP the rest of
// the setup (MikroTik reservations, walled-garden rules, port forwards)
// assumed it was on. Re-running the same apply logic at server startup
// closes that gap without requiring anyone to be there to click the button.
async function reapplyStaticNetworkOnBoot(db) {
  try {
    const type = db.prepare("SELECT value FROM settings WHERE key = 'network_type'").get()?.value;
    if (type !== 'static') return;

    const ip = db.prepare("SELECT value FROM settings WHERE key = 'static_ip'").get()?.value;
    const gateway = db.prepare("SELECT value FROM settings WHERE key = 'static_gateway'").get()?.value;
    const dns = db.prepare("SELECT value FROM settings WHERE key = 'static_dns'").get()?.value;
    const subnet = db.prepare("SELECT value FROM settings WHERE key = 'static_subnet'").get()?.value;
    if (!ip || !gateway) return;

    await applyNetworkConfig({ type: 'static', ip, gateway, dns, subnet });
    console.log(`🌐 Static IP re-applied on boot: ${ip}`);
  } catch (err) {
    console.error('Could not re-apply static network config on boot:', err.message);
  }
}

module.exports = { getPrimaryInterface, applyNetworkConfig, reapplyStaticNetworkOnBoot };
