// ===== ONLINE MOVIE CATALOG (vidrock.ru embed titles) =====
// Server-side source of truth for which TMDb ids are rentable online and
// at what price - kept separate from server/services/movieService.js (the
// LOCAL file-based catalog) on purpose, so nothing here ever touches that
// pipeline. The client's public/portal/assets/js/movies-online.js does NOT
// duplicate this data - it fetches the catalog live from
// GET /api/portal/online-movies, so this file is the single source of
// truth for both display and enforcement.
//
// Every title the owner sent across the original batches is included here.
// Anything not explicitly priced defaults to tier: 'free' (unlocked by any
// active WiFi session, same rule as a local free movie) - only the titles
// below tagged 'popular'/'premium'/'vip' need their own separate coin
// payment (see server/routes/coin.js's 'online_movie' mode).
//
// `poster` is null until real poster art is wired in (TMDb's image API,
// which needs its own free API key - ask before enabling since it means
// this box starts making outbound calls to themoviedb.org).

const CATALOG = [
  // FREE
  { id: 4951, title: "10 Things I Hate About You", tier: 'free', price_pesos: 0 },
  { id: 14161, title: '2012', tier: 'free', price_pesos: 0 },
  { id: 64688, title: '21 Jump Street', tier: 'free', price_pesos: 0 },
  { id: 187017, title: '22 Jump Street', tier: 'free', price_pesos: 0 },
  { id: 9487, title: "A Bug's Life", tier: 'free', price_pesos: 0 },
  { id: 11247, title: 'A Cinderella Story', tier: 'free', price_pesos: 0 },
  { id: 447332, title: 'A Quiet Place', tier: 'free', price_pesos: 0 },
  { id: 520962, title: 'A Quiet Place Part II', tier: 'free', price_pesos: 0 },
  { id: 762441, title: 'A Quiet Place: Day One', tier: 'free', price_pesos: 0 },
  { id: 10229, title: 'A Walk to Remember', tier: 'free', price_pesos: 0 },
  { id: 537915, title: 'After', tier: 'free', price_pesos: 0 },
  { id: 744276, title: 'After Ever Happy', tier: 'free', price_pesos: 0 },
  { id: 820525, title: 'After Everything', tier: 'free', price_pesos: 0 },
  { id: 613504, title: 'After We Collided', tier: 'free', price_pesos: 0 },
  { id: 744275, title: 'After We Fell', tier: 'free', price_pesos: 0 },
  { id: 420818, title: 'Aladdin', tier: 'free', price_pesos: 0 },
  { id: 399579, title: 'Alita: Battle Angel', tier: 'free', price_pesos: 0 },
  { id: 818750, title: 'Along for the Ride', tier: 'free', price_pesos: 0 },
  { id: 13448, title: 'Angels & Demons', tier: 'free', price_pesos: 0 },
  { id: 250546, title: 'Annabelle', tier: 'free', price_pesos: 0 },
  { id: 521029, title: 'Annabelle Comes Home', tier: 'free', price_pesos: 0 },
  { id: 396493, title: 'Annabelle: Creation', tier: 'free', price_pesos: 0 },
  { id: 15455, title: 'Another Cinderella Story', tier: 'free', price_pesos: 0 },
  { id: 363088, title: 'Ant-Man and the Wasp', tier: 'free', price_pesos: 0 },
  { id: 640146, title: 'Ant-Man and the Wasp: Quantumania', tier: 'free', price_pesos: 0 },
  { id: 1072790, title: 'Anyone But You', tier: 'free', price_pesos: 0 },
  { id: 297802, title: 'Aquaman', tier: 'free', price_pesos: 0 },
  { id: 572802, title: 'Aquaman and the Lost Kingdom', tier: 'free', price_pesos: 0 },
  { id: 272, title: 'Batman Begins', tier: 'free', price_pesos: 0 },
  { id: 209112, title: 'Batman v Superman: Dawn of Justice', tier: 'free', price_pesos: 0 },
  { id: 321612, title: 'Beauty and the Beast', tier: 'free', price_pesos: 0 },
  { id: 177572, title: 'Big Hero 6', tier: 'free', price_pesos: 0 },
  { id: 436270, title: 'Black Adam', tier: 'free', price_pesos: 0 },
  { id: 335984, title: 'Blade Runner 2049', tier: 'free', price_pesos: 0 },
  { id: 439079, title: 'Booksmart', tier: 'free', price_pesos: 0 },
  { id: 424783, title: 'Bumblebee', tier: 'free', price_pesos: 0 },
  { id: 11631, title: 'Camp Rock', tier: 'free', price_pesos: 0 },
  { id: 41507, title: 'Camp Rock 2: The Final Jam', tier: 'free', price_pesos: 0 },
  { id: 100402, title: 'Captain America: The Winter Soldier', tier: 'free', price_pesos: 0 },
  { id: 299537, title: 'Captain Marvel', tier: 'free', price_pesos: 0 },
  { id: 920, title: 'Cars', tier: 'free', price_pesos: 0 },
  { id: 49013, title: 'Cars 2', tier: 'free', price_pesos: 0 },
  { id: 260514, title: 'Cars 3', tier: 'free', price_pesos: 0 },
  { id: 302699, title: 'Central Intelligence', tier: 'free', price_pesos: 0 },
  { id: 150689, title: 'Cinderella', tier: 'free', price_pesos: 0 },
  { id: 9603, title: 'Clueless', tier: 'free', price_pesos: 0 },
  { id: 354912, title: 'Coco', tier: 'free', price_pesos: 0 },
  { id: 337404, title: 'Cruella', tier: 'free', price_pesos: 0 },
  { id: 20352, title: 'Despicable Me', tier: 'free', price_pesos: 0 },
  { id: 93456, title: 'Despicable Me 2', tier: 'free', price_pesos: 0 },
  { id: 324852, title: 'Despicable Me 3', tier: 'free', price_pesos: 0 },
  { id: 519182, title: 'Despicable Me 4', tier: 'free', price_pesos: 0 },
  { id: 447404, title: 'Detective Pikachu', tier: 'free', price_pesos: 0 },
  { id: 639933, title: 'Do Revenge', tier: 'free', price_pesos: 0 },
  { id: 37735, title: 'Easy A', tier: 'free', price_pesos: 0 },
  { id: 489925, title: 'Eighth Grade', tier: 'free', price_pesos: 0 },
  { id: 976573, title: 'Elemental', tier: 'free', price_pesos: 0 },
  { id: 568124, title: 'Encanto', tier: 'free', price_pesos: 0 },
  { id: 497582, title: 'Enola Holmes', tier: 'free', price_pesos: 0 },
  { id: 829280, title: 'Enola Holmes 2', tier: 'free', price_pesos: 0 },
  { id: 522681, title: 'Escape Room', tier: 'free', price_pesos: 0 },
  { id: 585216, title: 'Escape Room: Tournament of Champions', tier: 'free', price_pesos: 0 },
  { id: 524434, title: 'Eternals', tier: 'free', price_pesos: 0 },
  { id: 385128, title: 'F9', tier: 'free', price_pesos: 0 },
  { id: 259316, title: 'Fantastic Beasts and Where to Find Them', tier: 'free', price_pesos: 0 },
  { id: 338952, title: 'Fantastic Beasts: The Crimes of Grindelwald', tier: 'free', price_pesos: 0 },
  { id: 338953, title: 'Fantastic Beasts: The Secrets of Dumbledore', tier: 'free', price_pesos: 0 },
  { id: 22803, title: 'Fast & Furious', tier: 'free', price_pesos: 0 },
  { id: 385687, title: 'Fast X', tier: 'free', price_pesos: 0 },
  { id: 9377, title: "Ferris Bueller's Day Off", tier: 'free', price_pesos: 0 },
  { id: 127380, title: 'Finding Dory', tier: 'free', price_pesos: 0 },
  { id: 12, title: 'Finding Nemo', tier: 'free', price_pesos: 0 },
  { id: 527641, title: 'Five Feet Apart', tier: 'free', price_pesos: 0 },
  { id: 507089, title: "Five Nights at Freddy's", tier: 'free', price_pesos: 0 },
  { id: 1957, title: 'Freaky Friday', tier: 'free', price_pesos: 0 },
  { id: 550988, title: 'Free Guy', tier: 'free', price_pesos: 0 },
  { id: 109445, title: 'Frozen', tier: 'free', price_pesos: 0 },
  { id: 330457, title: 'Frozen II', tier: 'free', price_pesos: 0 },
  { id: 274855, title: 'Geostorm', tier: 'free', price_pesos: 0 },
  { id: 124905, title: 'Godzilla', tier: 'free', price_pesos: 0 },
  { id: 399566, title: 'Godzilla vs. Kong', tier: 'free', price_pesos: 0 },
  { id: 373571, title: 'Godzilla: King of the Monsters', tier: 'free', price_pesos: 0 },
  { id: 38365, title: 'Grown Ups', tier: 'free', price_pesos: 0 },
  { id: 109418, title: 'Grown Ups 2', tier: 'free', price_pesos: 0 },
  { id: 447365, title: 'Guardians of the Galaxy Vol. 3', tier: 'free', price_pesos: 0 },
  { id: 948, title: 'Halloween', tier: 'free', price_pesos: 0 },
  { id: 424139, title: 'Halloween (2018)', tier: 'free', price_pesos: 0 },
  { id: 616820, title: 'Halloween Ends', tier: 'free', price_pesos: 0 },
  { id: 610128, title: 'Halloween Kills', tier: 'free', price_pesos: 0 },
  { id: 440021, title: 'Happy Death Day', tier: 'free', price_pesos: 0 },
  { id: 672, title: 'Harry Potter and the Chamber of Secrets', tier: 'free', price_pesos: 0 },
  { id: 12444, title: 'Harry Potter and the Deathly Hallows: Part 1', tier: 'free', price_pesos: 0 },
  { id: 674, title: 'Harry Potter and the Goblet of Fire', tier: 'free', price_pesos: 0 },
  { id: 767, title: 'Harry Potter and the Half-Blood Prince', tier: 'free', price_pesos: 0 },
  { id: 675, title: 'Harry Potter and the Order of the Phoenix', tier: 'free', price_pesos: 0 },
  { id: 673, title: 'Harry Potter and the Prisoner of Azkaban', tier: 'free', price_pesos: 0 },
  { id: 671, title: "Harry Potter and the Sorcerer's Stone", tier: 'free', price_pesos: 0 },
  { id: 678580, title: "He's All That", tier: 'free', price_pesos: 0 },
  { id: 10947, title: 'High School Musical', tier: 'free', price_pesos: 0 },
  { id: 13649, title: 'High School Musical 2', tier: 'free', price_pesos: 0 },
  { id: 11887, title: 'High School Musical 3: Senior Year', tier: 'free', price_pesos: 0 },
  { id: 384018, title: 'Hobbs & Shaw', tier: 'free', price_pesos: 0 },
  { id: 76492, title: 'Hotel Transylvania', tier: 'free', price_pesos: 0 },
  { id: 159824, title: 'Hotel Transylvania 2', tier: 'free', price_pesos: 0 },
  { id: 400155, title: 'Hotel Transylvania 3: Summer Vacation', tier: 'free', price_pesos: 0 },
  { id: 585083, title: 'Hotel Transylvania: Transformania', tier: 'free', price_pesos: 0 },
  { id: 10191, title: 'How to Train Your Dragon', tier: 'free', price_pesos: 0 },
  { id: 82702, title: 'How to Train Your Dragon 2', tier: 'free', price_pesos: 0 },
  { id: 166428, title: 'How to Train Your Dragon: The Hidden World', tier: 'free', price_pesos: 0 },
  { id: 6479, title: 'I Am Legend', tier: 'free', price_pesos: 0 },
  { id: 260513, title: 'Incredibles 2', tier: 'free', price_pesos: 0 },
  { id: 602, title: 'Independence Day', tier: 'free', price_pesos: 0 },
  { id: 150540, title: 'Inside Out', tier: 'free', price_pesos: 0 },
  { id: 49018, title: 'Insidious', tier: 'free', price_pesos: 0 },
  { id: 91586, title: 'Insidious: Chapter 2', tier: 'free', price_pesos: 0 },
  { id: 614479, title: 'Insidious: The Red Door', tier: 'free', price_pesos: 0 },
  { id: 10138, title: 'Iron Man 2', tier: 'free', price_pesos: 0 },
  { id: 68721, title: 'Iron Man 3', tier: 'free', price_pesos: 0 },
  { id: 346364, title: 'It', tier: 'free', price_pesos: 0 },
  { id: 474350, title: 'It Chapter Two', tier: 'free', price_pesos: 0 },
  { id: 245891, title: 'John Wick', tier: 'free', price_pesos: 0 },
  { id: 324552, title: 'John Wick: Chapter 2', tier: 'free', price_pesos: 0 },
  { id: 458156, title: 'John Wick: Chapter 3 - Parabellum', tier: 'free', price_pesos: 0 },
  { id: 889737, title: 'Joker: Folie à Deux', tier: 'free', price_pesos: 0 },
  { id: 8844, title: 'Jumanji', tier: 'free', price_pesos: 0 },
  { id: 451048, title: 'Jungle Cruise', tier: 'free', price_pesos: 0 },
  { id: 331, title: 'Jurassic Park III', tier: 'free', price_pesos: 0 },
  { id: 507086, title: 'Jurassic World Dominion', tier: 'free', price_pesos: 0 },
  { id: 141052, title: 'Justice League', tier: 'free', price_pesos: 0 },
  { id: 254, title: 'King Kong', tier: 'free', price_pesos: 0 },
  { id: 293167, title: 'Kong: Skull Island', tier: 'free', price_pesos: 0 },
  { id: 9502, title: 'Kung Fu Panda', tier: 'free', price_pesos: 0 },
  { id: 49444, title: 'Kung Fu Panda 2', tier: 'free', price_pesos: 0 },
  { id: 140300, title: 'Kung Fu Panda 3', tier: 'free', price_pesos: 0 },
  { id: 1011985, title: 'Kung Fu Panda 4', tier: 'free', price_pesos: 0 },
  { id: 391713, title: 'Lady Bird', tier: 'free', price_pesos: 0 },
  { id: 345911, title: 'Lights Out', tier: 'free', price_pesos: 0 },
  { id: 11544, title: 'Lilo & Stitch', tier: 'free', price_pesos: 0 },
  { id: 20760, title: 'Lilo & Stitch 2: Stitch Has a Glitch', tier: 'free', price_pesos: 0 },
  { id: 449176, title: 'Love, Simon', tier: 'free', price_pesos: 0 },
  { id: 508943, title: 'Luca', tier: 'free', price_pesos: 0 },
  { id: 536554, title: 'M3GAN', tier: 'free', price_pesos: 0 },
  { id: 1071585, title: 'M3GAN 2.0', tier: 'free', price_pesos: 0 },
  { id: 953, title: 'Madagascar', tier: 'free', price_pesos: 0 },
  { id: 80321, title: "Madagascar 3: Europe's Most Wanted", tier: 'free', price_pesos: 0 },
  { id: 10527, title: 'Madagascar: Escape 2 Africa', tier: 'free', price_pesos: 0 },
  { id: 102651, title: 'Maleficent', tier: 'free', price_pesos: 0 },
  { id: 420809, title: 'Maleficent: Mistress of Evil', tier: 'free', price_pesos: 0 },
  { id: 49521, title: 'Man of Steel', tier: 'free', price_pesos: 0 },
  { id: 336843, title: 'Maze Runner: The Death Cure', tier: 'free', price_pesos: 0 },
  { id: 294254, title: 'Maze Runner: The Scorch Trials', tier: 'free', price_pesos: 0 },
  { id: 296096, title: 'Me Before You', tier: 'free', price_pesos: 0 },
  { id: 10625, title: 'Mean Girls', tier: 'free', price_pesos: 0 },
  { id: 673593, title: 'Mean Girls (2024)', tier: 'free', price_pesos: 0 },
  { id: 38055, title: 'Megamind', tier: 'free', price_pesos: 0 },
  { id: 211672, title: 'Minions', tier: 'free', price_pesos: 0 },
  { id: 438148, title: 'Minions: The Rise of Gru', tier: 'free', price_pesos: 0 },
  { id: 954, title: 'Mission: Impossible', tier: 'free', price_pesos: 0 },
  { id: 575264, title: 'Mission: Impossible - Dead Reckoning Part One', tier: 'free', price_pesos: 0 },
  { id: 56292, title: 'Mission: Impossible - Ghost Protocol', tier: 'free', price_pesos: 0 },
  { id: 177677, title: 'Mission: Impossible - Rogue Nation', tier: 'free', price_pesos: 0 },
  { id: 955, title: 'Mission: Impossible 2', tier: 'free', price_pesos: 0 },
  { id: 956, title: 'Mission: Impossible III', tier: 'free', price_pesos: 0 },
  { id: 277834, title: 'Moana', tier: 'free', price_pesos: 0 },
  { id: 62211, title: 'Monsters University', tier: 'free', price_pesos: 0 },
  { id: 585, title: 'Monsters, Inc.', tier: 'free', price_pesos: 0 },
  { id: 762509, title: 'Mufasa: The Lion King', tier: 'free', price_pesos: 0 },
  { id: 337401, title: 'Mulan (1998)', tier: 'free', price_pesos: 0 },
  { id: 10674, title: 'Mulan (2020)', tier: 'free', price_pesos: 0 },
  { id: 1010581, title: 'My Fault', tier: 'free', price_pesos: 0 },
  { id: 2059, title: 'National Treasure', tier: 'free', price_pesos: 0 },
  { id: 6639, title: 'National Treasure: Book of Secrets', tier: 'free', price_pesos: 0 },
  { id: 195589, title: 'Neighbors', tier: 'free', price_pesos: 0 },
  { id: 325133, title: 'Neighbors 2: Sorority Rising', tier: 'free', price_pesos: 0 },
  { id: 615457, title: 'Nobody', tier: 'free', price_pesos: 0 },
  { id: 75656, title: 'Now You See Me', tier: 'free', price_pesos: 0 },
  { id: 291805, title: 'Now You See Me 2', tier: 'free', price_pesos: 0 },
  { id: 161, title: "Ocean's Eleven", tier: 'free', price_pesos: 0 },
  { id: 298, title: "Ocean's Thirteen", tier: 'free', price_pesos: 0 },
  { id: 163, title: "Ocean's Twelve", tier: 'free', price_pesos: 0 },
  { id: 508439, title: 'Onward', tier: 'free', price_pesos: 0 },
  { id: 21208, title: 'Orphan', tier: 'free', price_pesos: 0 },
  { id: 630586, title: 'Orphan: First Kill', tier: 'free', price_pesos: 0 },
  { id: 1156594, title: 'Our Fault', tier: 'free', price_pesos: 0 },
  { id: 68726, title: 'Pacific Rim', tier: 'free', price_pesos: 0 },
  { id: 268896, title: 'Pacific Rim: Uprising', tier: 'free', price_pesos: 0 },
  { id: 32657, title: 'Percy Jackson & the Olympians: The Lightning Thief', tier: 'free', price_pesos: 0 },
  { id: 76285, title: 'Percy Jackson: Sea of Monsters', tier: 'free', price_pesos: 0 },
  { id: 285, title: "Pirates of the Caribbean: At World's End", tier: 'free', price_pesos: 0 },
  { id: 58, title: "Pirates of the Caribbean: Dead Man's Chest", tier: 'free', price_pesos: 0 },
  { id: 166426, title: 'Pirates of the Caribbean: Dead Men Tell No Tales', tier: 'free', price_pesos: 0 },
  { id: 1865, title: 'Pirates of the Caribbean: On Stranger Tides', tier: 'free', price_pesos: 0 },
  { id: 256092, title: 'Pitch Perfect 2', tier: 'free', price_pesos: 0 },
  { id: 353616, title: 'Pitch Perfect 3', tier: 'free', price_pesos: 0 },
  { id: 571891, title: 'Pokémon: Mewtwo Strikes Back - Evolution', tier: 'free', price_pesos: 0 },
  { id: 57214, title: 'Project X', tier: 'free', price_pesos: 0 },
  { id: 417859, title: 'Puss in Boots', tier: 'free', price_pesos: 0 },
  { id: 315162, title: 'Puss in Boots: The Last Wish', tier: 'free', price_pesos: 0 },
  { id: 404368, title: 'Ralph Breaks the Internet', tier: 'free', price_pesos: 0 },
  { id: 427641, title: 'Rampage', tier: 'free', price_pesos: 0 },
  { id: 2062, title: 'Ratatouille', tier: 'free', price_pesos: 0 },
  { id: 527774, title: 'Raya and the Last Dragon', tier: 'free', price_pesos: 0 },
  { id: 333339, title: 'Ready Player One', tier: 'free', price_pesos: 0 },
  { id: 512195, title: 'Red Notice', tier: 'free', price_pesos: 0 },
  { id: 184345, title: 'Ride Along', tier: 'free', price_pesos: 0 },
  { id: 323675, title: 'Ride Along 2', tier: 'free', price_pesos: 0 },
  { id: 2109, title: 'Rush Hour', tier: 'free', price_pesos: 0 },
  { id: 5175, title: 'Rush Hour 2', tier: 'free', price_pesos: 0 },
  { id: 5174, title: 'Rush Hour 3', tier: 'free', price_pesos: 0 },
  { id: 254128, title: 'San Andreas', tier: 'free', price_pesos: 0 },
  { id: 4247, title: 'Scary Movie', tier: 'free', price_pesos: 0 },
  { id: 4248, title: 'Scary Movie 2', tier: 'free', price_pesos: 0 },
  { id: 4256, title: 'Scary Movie 3', tier: 'free', price_pesos: 0 },
  { id: 4257, title: 'Scary Movie 4', tier: 'free', price_pesos: 0 },
  { id: 4258, title: 'Scary Movie 5', tier: 'free', price_pesos: 0 },
  { id: 4232, title: 'Scream (1996)', tier: 'free', price_pesos: 0 },
  { id: 646385, title: 'Scream (2022)', tier: 'free', price_pesos: 0 },
  { id: 41446, title: 'Scream 4', tier: 'free', price_pesos: 0 },
  { id: 934433, title: 'Scream VI', tier: 'free', price_pesos: 0 },
  { id: 566525, title: 'Shang-Chi and the Legend of the Ten Rings', tier: 'free', price_pesos: 0 },
  { id: 287947, title: 'Shazam!', tier: 'free', price_pesos: 0 },
  { id: 594767, title: 'Shazam! Fury of the Gods', tier: 'free', price_pesos: 0 },
  { id: 9655, title: "She's the Man", tier: 'free', price_pesos: 0 },
  { id: 808, title: 'Shrek', tier: 'free', price_pesos: 0 },
  { id: 809, title: 'Shrek 2', tier: 'free', price_pesos: 0 },
  { id: 10192, title: 'Shrek Forever After', tier: 'free', price_pesos: 0 },
  { id: 810, title: 'Shrek the Third', tier: 'free', price_pesos: 0 },
  { id: 454293, title: 'Sierra Burgess Is a Loser', tier: 'free', price_pesos: 0 },
  { id: 335797, title: 'Sing', tier: 'free', price_pesos: 0 },
  { id: 438695, title: 'Sing 2', tier: 'free', price_pesos: 0 },
  { id: 447200, title: 'Skyscraper', tier: 'free', price_pesos: 0 },
  { id: 882598, title: 'Smile', tier: 'free', price_pesos: 0 },
  { id: 1100782, title: 'Smile 2', tier: 'free', price_pesos: 0 },
  { id: 454626, title: 'Sonic the Hedgehog', tier: 'free', price_pesos: 0 },
  { id: 675353, title: 'Sonic the Hedgehog 2', tier: 'free', price_pesos: 0 },
  { id: 508442, title: 'Soul', tier: 'free', price_pesos: 0 },
  { id: 559, title: 'Spider-Man 3', tier: 'free', price_pesos: 0 },
  { id: 569094, title: 'Spider-Man: Across the Spider-Verse', tier: 'free', price_pesos: 0 },
  { id: 235, title: 'Stand by Me', tier: 'free', price_pesos: 0 },
  { id: 8363, title: 'Superbad', tier: 'free', price_pesos: 0 },
  { id: 8681, title: 'Taken', tier: 'free', price_pesos: 0 },
  { id: 82675, title: 'Taken 2', tier: 'free', price_pesos: 0 },
  { id: 260346, title: 'Taken 3', tier: 'free', price_pesos: 0 },
  { id: 1001311, title: 'Talk to Me', tier: 'free', price_pesos: 0 },
  { id: 38757, title: 'Tangled', tier: 'free', price_pesos: 0 },
  { id: 1930, title: 'The Amazing Spider-Man', tier: 'free', price_pesos: 0 },
  { id: 102382, title: 'The Amazing Spider-Man 2', tier: 'free', price_pesos: 0 },
  { id: 24428, title: 'The Avengers', tier: 'free', price_pesos: 0 },
  { id: 756999, title: 'The Black Phone', tier: 'free', price_pesos: 0 },
  { id: 295693, title: 'The Boss Baby', tier: 'free', price_pesos: 0 },
  { id: 459151, title: 'The Boss Baby: Family Business', tier: 'free', price_pesos: 0 },
  { id: 2108, title: 'The Breakfast Club', tier: 'free', price_pesos: 0 },
  { id: 2454, title: 'The Chronicles of Narnia: Prince Caspian', tier: 'free', price_pesos: 0 },
  { id: 411, title: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', tier: 'free', price_pesos: 0 },
  { id: 10140, title: 'The Chronicles of Narnia: The Voyage of the Dawn Treader', tier: 'free', price_pesos: 0 },
  { id: 138843, title: 'The Conjuring', tier: 'free', price_pesos: 0 },
  { id: 259693, title: 'The Conjuring 2', tier: 'free', price_pesos: 0 },
  { id: 423108, title: 'The Conjuring: The Devil Made Me Do It', tier: 'free', price_pesos: 0 },
  { id: 49519, title: 'The Croods', tier: 'free', price_pesos: 0 },
  { id: 529203, title: 'The Croods: A New Age', tier: 'free', price_pesos: 0 },
  { id: 272693, title: 'The DUFF', tier: 'free', price_pesos: 0 },
  { id: 591, title: 'The Da Vinci Code', tier: 'free', price_pesos: 0 },
  { id: 49026, title: 'The Dark Knight Rises', tier: 'free', price_pesos: 0 },
  { id: 435, title: 'The Day After Tomorrow', tier: 'free', price_pesos: 0 },
  { id: 262504, title: 'The Divergent Series: Allegiant', tier: 'free', price_pesos: 0 },
  { id: 262500, title: 'The Divergent Series: Insurgent', tier: 'free', price_pesos: 0 },
  { id: 376867, title: 'The Edge of Seventeen', tier: 'free', price_pesos: 0 },
  { id: 156022, title: 'The Equalizer', tier: 'free', price_pesos: 0 },
  { id: 345887, title: 'The Equalizer 2', tier: 'free', price_pesos: 0 },
  { id: 926393, title: 'The Equalizer 3', tier: 'free', price_pesos: 0 },
  { id: 9552, title: 'The Exorcist', tier: 'free', price_pesos: 0 },
  { id: 795514, title: 'The Fallout', tier: 'free', price_pesos: 0 },
  { id: 337339, title: 'The Fate of the Furious', tier: 'free', price_pesos: 0 },
  { id: 222935, title: 'The Fault in Our Stars', tier: 'free', price_pesos: 0 },
  { id: 298618, title: 'The Flash', tier: 'free', price_pesos: 0 },
  { id: 105864, title: 'The Good Dinosaur', tier: 'free', price_pesos: 0 },
  { id: 1970, title: 'The Grudge', tier: 'free', price_pesos: 0 },
  { id: 609249, title: 'The Half of It', tier: 'free', price_pesos: 0 },
  { id: 18785, title: 'The Hangover', tier: 'free', price_pesos: 0 },
  { id: 45243, title: 'The Hangover Part II', tier: 'free', price_pesos: 0 },
  { id: 109439, title: 'The Hangover Part III', tier: 'free', price_pesos: 0 },
  { id: 470044, title: 'The Hate U Give', tier: 'free', price_pesos: 0 },
  { id: 49051, title: 'The Hobbit: An Unexpected Journey', tier: 'free', price_pesos: 0 },
  { id: 122917, title: 'The Hobbit: The Battle of the Five Armies', tier: 'free', price_pesos: 0 },
  { id: 57158, title: 'The Hobbit: The Desolation of Smaug', tier: 'free', price_pesos: 0 },
  { id: 131631, title: 'The Hunger Games: Mockingjay - Part 1', tier: 'free', price_pesos: 0 },
  { id: 131634, title: 'The Hunger Games: Mockingjay - Part 2', tier: 'free', price_pesos: 0 },
  { id: 695721, title: 'The Hunger Games: The Ballad of Songbirds & Snakes', tier: 'free', price_pesos: 0 },
  { id: 9806, title: 'The Incredibles', tier: 'free', price_pesos: 0 },
  { id: 9654, title: 'The Italian Job', tier: 'free', price_pesos: 0 },
  { id: 278927, title: 'The Jungle Book', tier: 'free', price_pesos: 0 },
  { id: 1880, title: 'The Karate Kid', tier: 'free', price_pesos: 0 },
  { id: 454983, title: 'The Kissing Booth', tier: 'free', price_pesos: 0 },
  { id: 583083, title: 'The Kissing Booth 2', tier: 'free', price_pesos: 0 },
  { id: 727745, title: 'The Kissing Booth 3', tier: 'free', price_pesos: 0 },
  { id: 35690, title: 'The Last Song', tier: 'free', price_pesos: 0 },
  { id: 8587, title: 'The Lion King (1994)', tier: 'free', price_pesos: 0 },
  { id: 9732, title: "The Lion King II: Simba's Pride", tier: 'free', price_pesos: 0 },
  { id: 447277, title: 'The Little Mermaid', tier: 'free', price_pesos: 0 },
  { id: 228205, title: 'The Longest Ride', tier: 'free', price_pesos: 0 },
  { id: 120, title: 'The Lord of the Rings: The Fellowship of the Ring', tier: 'free', price_pesos: 0 },
  { id: 121, title: 'The Lord of the Rings: The Two Towers', tier: 'free', price_pesos: 0 },
  { id: 752623, title: 'The Lost City', tier: 'free', price_pesos: 0 },
  { id: 330, title: 'The Lost World: Jurassic Park', tier: 'free', price_pesos: 0 },
  { id: 609681, title: 'The Marvels', tier: 'free', price_pesos: 0 },
  { id: 603, title: 'The Matrix', tier: 'free', price_pesos: 0 },
  { id: 604, title: 'The Matrix Reloaded', tier: 'free', price_pesos: 0 },
  { id: 624860, title: 'The Matrix Resurrections', tier: 'free', price_pesos: 0 },
  { id: 605, title: 'The Matrix Revolutions', tier: 'free', price_pesos: 0 },
  { id: 564, title: 'The Mummy', tier: 'free', price_pesos: 0 },
  { id: 1734, title: 'The Mummy Returns', tier: 'free', price_pesos: 0 },
  { id: 1735, title: 'The Mummy: Tomb of the Dragon Emperor', tier: 'free', price_pesos: 0 },
  { id: 11036, title: 'The Notebook', tier: 'free', price_pesos: 0 },
  { id: 968051, title: 'The Nun II', tier: 'free', price_pesos: 0 },
  { id: 227, title: 'The Outsiders', tier: 'free', price_pesos: 0 },
  { id: 559165, title: 'The Perfect Date', tier: 'free', price_pesos: 0 },
  { id: 84892, title: 'The Perks of Being a Wallflower', tier: 'free', price_pesos: 0 },
  { id: 9880, title: 'The Princess Diaries', tier: 'free', price_pesos: 0 },
  { id: 12118, title: 'The Princess Diaries 2: Royal Engagement', tier: 'free', price_pesos: 0 },
  { id: 10198, title: 'The Princess and the Frog', tier: 'free', price_pesos: 0 },
  { id: 565, title: 'The Ring', tier: 'free', price_pesos: 0 },
  { id: 328111, title: 'The Secret Life of Pets', tier: 'free', price_pesos: 0 },
  { id: 412117, title: 'The Secret Life of Pets 2', tier: 'free', price_pesos: 0 },
  { id: 157386, title: 'The Spectacular Now', tier: 'free', price_pesos: 0 },
  { id: 436969, title: 'The Suicide Squad', tier: 'free', price_pesos: 0 },
  { id: 502356, title: 'The Super Mario Bros. Movie', tier: 'free', price_pesos: 0 },
  { id: 30497, title: 'The Texas Chainsaw Massacre', tier: 'free', price_pesos: 0 },
  { id: 4108, title: 'The Transporter', tier: 'free', price_pesos: 0 },
  { id: 50619, title: 'The Twilight Saga: Breaking Dawn - Part 1', tier: 'free', price_pesos: 0 },
  { id: 50620, title: 'The Twilight Saga: Breaking Dawn - Part 2', tier: 'free', price_pesos: 0 },
  { id: 24021, title: 'The Twilight Saga: Eclipse', tier: 'free', price_pesos: 0 },
  { id: 18239, title: 'The Twilight Saga: New Moon', tier: 'free', price_pesos: 0 },
  { id: 39210, title: 'The Vow', tier: 'free', price_pesos: 0 },
  { id: 630, title: 'The Wizard of Oz', tier: 'free', price_pesos: 0 },
  { id: 616037, title: 'Thor: Love and Thunder', tier: 'free', price_pesos: 0 },
  { id: 76338, title: 'Thor: The Dark World', tier: 'free', price_pesos: 0 },
  { id: 466282, title: "To All the Boys I've Loved Before", tier: 'free', price_pesos: 0 },
  { id: 614409, title: 'To All the Boys: Always and Forever', tier: 'free', price_pesos: 0 },
  { id: 565426, title: 'To All the Boys: P.S. I Still Love You', tier: 'free', price_pesos: 0 },
  { id: 338970, title: 'Tomb Raider', tier: 'free', price_pesos: 0 },
  { id: 1996, title: 'Tomb Raider: The Cradle of Life', tier: 'free', price_pesos: 0 },
  { id: 744, title: 'Top Gun', tier: 'free', price_pesos: 0 },
  { id: 862, title: 'Toy Story', tier: 'free', price_pesos: 0 },
  { id: 863, title: 'Toy Story 2', tier: 'free', price_pesos: 0 },
  { id: 10193, title: 'Toy Story 3', tier: 'free', price_pesos: 0 },
  { id: 301528, title: 'Toy Story 4', tier: 'free', price_pesos: 0 },
  { id: 91314, title: 'Transformers: Age of Extinction', tier: 'free', price_pesos: 0 },
  { id: 38356, title: 'Transformers: Dark of the Moon', tier: 'free', price_pesos: 0 },
  { id: 8373, title: 'Transformers: Revenge of the Fallen', tier: 'free', price_pesos: 0 },
  { id: 335988, title: 'Transformers: The Last Knight', tier: 'free', price_pesos: 0 },
  { id: 9335, title: 'Transporter 2', tier: 'free', price_pesos: 0 },
  { id: 13387, title: 'Transporter 3', tier: 'free', price_pesos: 0 },
  { id: 136799, title: 'Trolls', tier: 'free', price_pesos: 0 },
  { id: 20526, title: 'Tron: Legacy', tier: 'free', price_pesos: 0 },
  { id: 460019, title: 'Truth or Dare', tier: 'free', price_pesos: 0 },
  { id: 508947, title: 'Turning Red', tier: 'free', price_pesos: 0 },
  { id: 335787, title: 'Uncharted', tier: 'free', price_pesos: 0 },
  { id: 14160, title: 'Up', tier: 'free', price_pesos: 0 },
  { id: 335983, title: 'Venom', tier: 'free', price_pesos: 0 },
  { id: 580489, title: 'Venom: Let There Be Carnage', tier: 'free', price_pesos: 0 },
  { id: 912649, title: 'Venom: The Last Dance', tier: 'free', price_pesos: 0 },
  { id: 10681, title: 'Wall-E', tier: 'free', price_pesos: 0 },
  { id: 74, title: 'War of the Worlds', tier: 'free', price_pesos: 0 },
  { id: 138832, title: "We're the Millers", tier: 'free', price_pesos: 0 },
  { id: 12153, title: 'White Chicks', tier: 'free', price_pesos: 0 },
  { id: 402431, title: 'Wicked', tier: 'free', price_pesos: 0 },
  { id: 967941, title: 'Wicked: For Good', tier: 'free', price_pesos: 0 },
  { id: 297762, title: 'Wonder Woman', tier: 'free', price_pesos: 0 },
  { id: 464052, title: 'Wonder Woman 1984', tier: 'free', price_pesos: 0 },
  { id: 787699, title: 'Wonka', tier: 'free', price_pesos: 0 },
  { id: 72190, title: 'World War Z', tier: 'free', price_pesos: 0 },
  { id: 82690, title: 'Wreck-It Ralph', tier: 'free', price_pesos: 0 },
  { id: 1156593, title: 'Your Fault', tier: 'free', price_pesos: 0 },
  { id: 269149, title: 'Zootopia', tier: 'free', price_pesos: 0 },

  // POPULAR - ₱10
  { id: 102899, title: 'Ant-Man', tier: 'popular', price_pesos: 10 },
  { id: 284054, title: 'Black Panther', tier: 'popular', price_pesos: 10 },
  { id: 1771, title: 'Captain America: The First Avenger', tier: 'popular', price_pesos: 10 },
  { id: 157350, title: 'Divergent', tier: 'popular', price_pesos: 10 },
  { id: 284052, title: 'Doctor Strange', tier: 'popular', price_pesos: 10 },
  { id: 51497, title: 'Fast Five', tier: 'popular', price_pesos: 10 },
  { id: 118340, title: 'Guardians of the Galaxy', tier: 'popular', price_pesos: 10 },
  { id: 1726, title: 'Iron Man', tier: 'popular', price_pesos: 10 },
  { id: 353486, title: 'Jumanji: Welcome to the Jungle', tier: 'popular', price_pesos: 10 },
  { id: 329, title: 'Jurassic Park', tier: 'popular', price_pesos: 10 },
  { id: 22, title: 'Pirates of the Caribbean: The Curse of the Black Pearl', tier: 'popular', price_pesos: 10 },
  { id: 114150, title: 'Pitch Perfect', tier: 'popular', price_pesos: 10 },
  { id: 557, title: 'Spider-Man', tier: 'popular', price_pesos: 10 },
  { id: 558, title: 'Spider-Man 2', tier: 'popular', price_pesos: 10 },
  { id: 316029, title: 'The Greatest Showman', tier: 'popular', price_pesos: 10 },
  { id: 70160, title: 'The Hunger Games', tier: 'popular', price_pesos: 10 },
  { id: 198663, title: 'The Maze Runner', tier: 'popular', price_pesos: 10 },
  { id: 10195, title: 'Thor', tier: 'popular', price_pesos: 10 },
  { id: 1858, title: 'Transformers', tier: 'popular', price_pesos: 10 },
  { id: 8966, title: 'Twilight', tier: 'popular', price_pesos: 10 },

  // PREMIUM - ₱15
  { id: 99861, title: 'Avengers: Age of Ultron', tier: 'premium', price_pesos: 15 },
  { id: 505642, title: 'Black Panther: Wakanda Forever', tier: 'premium', price_pesos: 15 },
  { id: 271110, title: 'Captain America: Civil War', tier: 'premium', price_pesos: 15 },
  { id: 293660, title: 'Deadpool', tier: 'premium', price_pesos: 15 },
  { id: 383498, title: 'Deadpool 2', tier: 'premium', price_pesos: 15 },
  { id: 453395, title: 'Doctor Strange in the Multiverse of Madness', tier: 'premium', price_pesos: 15 },
  { id: 438631, title: 'Dune', tier: 'premium', price_pesos: 15 },
  { id: 82992, title: 'Fast & Furious 6', tier: 'premium', price_pesos: 15 },
  { id: 168259, title: 'Furious 7', tier: 'premium', price_pesos: 15 },
  { id: 283995, title: 'Guardians of the Galaxy Vol. 2', tier: 'premium', price_pesos: 15 },
  { id: 512196, title: 'Jumanji: The Next Level', tier: 'premium', price_pesos: 15 },
  { id: 135397, title: 'Jurassic World', tier: 'premium', price_pesos: 15 },
  { id: 351286, title: 'Jurassic World: Fallen Kingdom', tier: 'premium', price_pesos: 15 },
  { id: 429617, title: 'Spider-Man: Far From Home', tier: 'premium', price_pesos: 15 },
  { id: 315635, title: 'Spider-Man: Homecoming', tier: 'premium', price_pesos: 15 },
  { id: 324857, title: 'Spider-Man: Into the Spider-Verse', tier: 'premium', price_pesos: 15 },
  { id: 414906, title: 'The Batman', tier: 'premium', price_pesos: 15 },
  { id: 284053, title: 'Thor: Ragnarok', tier: 'premium', price_pesos: 15 },
  { id: 361743, title: 'Top Gun: Maverick', tier: 'premium', price_pesos: 15 },
  { id: 667538, title: 'Transformers: Rise of the Beasts', tier: 'premium', price_pesos: 15 },

  // VIP - ₱20
  { id: 19995, title: 'Avatar', tier: 'vip', price_pesos: 20 },
  { id: 76600, title: 'Avatar: The Way of Water', tier: 'vip', price_pesos: 20 },
  { id: 299534, title: 'Avengers: Endgame', tier: 'vip', price_pesos: 20 },
  { id: 299536, title: 'Avengers: Infinity War', tier: 'vip', price_pesos: 20 },
  { id: 533535, title: 'Deadpool & Wolverine', tier: 'vip', price_pesos: 20 },
  { id: 693134, title: 'Dune: Part Two', tier: 'vip', price_pesos: 20 },
  { id: 823464, title: 'Godzilla x Kong: The New Empire', tier: 'vip', price_pesos: 20 },
  { id: 12445, title: 'Harry Potter and the Deathly Hallows: Part 2', tier: 'vip', price_pesos: 20 },
  { id: 27205, title: 'Inception', tier: 'vip', price_pesos: 20 },
  { id: 1022789, title: 'Inside Out 2', tier: 'vip', price_pesos: 20 },
  { id: 157336, title: 'Interstellar', tier: 'vip', price_pesos: 20 },
  { id: 603692, title: 'John Wick: Chapter 4', tier: 'vip', price_pesos: 20 },
  { id: 475557, title: 'Joker', tier: 'vip', price_pesos: 20 },
  { id: 353081, title: 'Mission: Impossible - Fallout', tier: 'vip', price_pesos: 20 },
  { id: 1241982, title: 'Moana 2', tier: 'vip', price_pesos: 20 },
  { id: 939243, title: 'Sonic the Hedgehog 3', tier: 'vip', price_pesos: 20 },
  { id: 634649, title: 'Spider-Man: No Way Home', tier: 'vip', price_pesos: 20 },
  { id: 155, title: 'The Dark Knight', tier: 'vip', price_pesos: 20 },
  { id: 101299, title: 'The Hunger Games: Catching Fire', tier: 'vip', price_pesos: 20 },
  { id: 122, title: 'The Lord of the Rings: The Return of the King', tier: 'vip', price_pesos: 20 },
];

const BY_ID = new Map(CATALOG.map((m) => [m.id, m]));

// Owner's call: launch with everything free while the coin-gate flow is
// still new, without losing the tier/price data already entered above.
// Flip this back to false whenever pricing should turn back on - no other
// change needed, since POST /pending (coin.js) already refuses to open a
// paid coin window for anything whose tier reads 'free'.
const FREE_FOR_ALL = true;

function applyFreeOverride(movie) {
  if (!FREE_FOR_ALL || movie.tier === 'free') return movie;
  return { ...movie, tier: 'free', price_pesos: 0 };
}

function getAll() {
  return CATALOG.map(applyFreeOverride);
}

function getById(id) {
  const movie = BY_ID.get(Number(id));
  return movie ? applyFreeOverride(movie) : null;
}

module.exports = { getAll, getById };
